import subprocess
import parmed

def PDBUniqueAtomNames(pdbfile):
    def count_in_array(array,element):
        i=0
        for val in array:
            if val == element:
                i+=1
        return i
    try:
        pdb = parmed.load_file(pdbfile)
    except:
        return
    atom_names = [atom.name for atom in pdb.atoms]
    if len(set(atom_names)) == len(atom_names):
        return
    elements = [atom.element_name for atom in pdb.atoms]
    atom_names = []
    for i,ele in enumerate(elements):
        n_ele = count_in_array(elements[:i],ele) + 1
        atom_names.append(f"{ele}{n_ele:>03}")
    for atom in pdb.atoms:
        atom.name = atom_names[atom.idx]
    parmed.write_PDB(pdb,pdbfile)

def PDBisTooBig(pdbfile):
    n_atoms = 0
    for line in open(pdbfile).readlines():
        if any(["ATOM" in line,"HETATM" in line]):
            n_atoms+=1
    return bool(n_atoms>500)

def SingleResidue(pdbfile):
    subprocess.call(f"cp {pdbfile} {pdbfile}.ORIG",shell=True)
    lines = open(pdbfile).readlines()
    # unique_atom_names = []
    get_res_info = True
    # element_count = {}
    atomcounts=0
    PDBUniqueAtomNames(pdbfile)
    for i,line in enumerate(lines):
        if any(["ATOM" in line,"HETATM" in line]):
            atomcounts +=1
            number=line[6:11].strip()
            if int(number)!= int(atomcounts):
                number=atomcounts
            atomname=line[12:16].strip()
            if get_res_info:
                resname=line[17:20].strip()
                resid=line[21:26].strip()
                get_res_info=False
            x = float(line[27:38].strip())
            y = float(line[39:46].strip())
            z = float(line[47:54].strip())
            element=line[76:78].strip()
            # if element not in element_count.keys():
            #     element_count[element] = 0
            # element_count[element] += 1
            # while atomname in unique_atom_names:
            #     atomname=f"{element}{element_count[element]:>03}"
            #     element_count[element] += 1
            # unique_atom_names.append(atomname)
            lines[i] = f"ATOM  {number:>5} {f'{atomname:>3}':<4} {resname:>3} {resid:>5} {x:>11.3f} {y:>7.3f} {z:>7.3f} {f'{element:>23}':<25}\n"
    with open(pdbfile,"w") as f:
        f.write("REMARK File generated by WalkerLabs AutoParametrizer.\n")
        for line in lines:
            if "ATOM" in line:
                f.write(line)
        f.write("TER\nEND\n")

def GetResName(pdb):
    for line in open(pdb,"r").readlines():
        if "ATOM" in line:
            return line[17:20].strip()

def RemoveCaps(pdbfile,cap_atoms):
    pdb = parmed.load_file(pdbfile)
    pdb.save("CAPPED_"+pdbfile)
    uncapped = parmed.Structure()
    for atom in pdb.atoms:
        if atom.name.strip() not in cap_atoms:
            uncapped.add_atom(atom,atom.residue.name,atom.residue.number)
    uncapped.save(pdbfile,overwrite=True)
